export const FETCH_HOMEPAGE_BLOG_REQUEST = 'FETCH_HOMEPAGE_BLOG_REQUEST';
export const FETCH_HOMEPAGE_BLOG_SUCCESS = 'FETCH_HOMEPAGE_BLOG_SUCCESS';
export const FETCH_HOMEPAGE_BLOG_ERROR = 'FETCH_HOMEPAGE_BLOG_ERROR';